{assign var=pageTitle value=$pageTitle|default:"No title"}
{assign var=pageContent value=$pageContent|default:"No content"}
{assign var=pageCharset value=$pageCharset|default:$smarty.const.SITE_DEFAULT_CHARSET}

<!DOCTYPE html>
<html lang="{$pageLanguageIdent}">
<head>
 <meta charset="{$pageCharset}"/>
 <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"/>
 <meta name="viewport" content="width=device-width, initial-scale=1"/>
 {include file="meta_data.tpl"}

 <!--[if lt IE 9]>
 <script src="/javascripts/html5shiv/dist/html5shiv.js"></script>
 <![endif]-->

 <title>{$pageTitle}</title>
 <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" />

 <!-- *** layout stylesheet *** -->
 <link rel="stylesheet" type="text/css" href="{$smarty.const.URI_STYLES|cat:'main.edit_80-blue.css'}" />
 <link rel="stylesheet" type="text/css" href="{$smarty.const.URI_STYLES|cat:'/fonts/font-awesome-4.0.3/css/font-awesome.css'}" />
 {* <link rel="stylesheet" href="/javascripts/jquery/jquery-ui/css/custom-theme/jquery-ui-latest.custom.min.css"/> *}
{literal}
 <style>
 @media only screen and (max-device-width: 479px) {
   html { background-image:url(/ai-cookie.php?maxwidth=479); }
 }
 @media only screen and (min-device-width: 480px) and (max-device-width: 767px) {
   html { background-image:url(/ai-cookie.php?maxwidth=767); }
 }
 @media only screen and (min-device-width: 768px) and (max-device-width: 991px) {
   html { background-image:url(/ai-cookie.php?maxwidth=991); }
 }
 @media only screen and (min-device-width: 992px) and (max-device-width: 1381px) {
   html { background-image:url(/ai-cookie.php?maxwidth=1381); }
 }
 @media only screen and (min-device-width: 1382px) {
   html { background-image:url(/ai-cookie.php?maxwidth=1600); }

 </style>
{/literal}
</head>

<body>
 {$pageContent}

{if $smarty.const.DEBUG}
  {if isset($debugContent)}
    {$debugContent}
  {/if}

  <div style="float:left; clear:both;">
    <a href="http://www.smarty.net" target="_blank" title="About Smarty">
      <img src="{$smarty.const.URI_GRAPHICS_COMMON|cat:'smarty-80x15.png'}" alt="Read about Smarty" style="vertical-align:text-bottom; border-style:none;"/>
    </a>
    <span><i>Template: <b>{$smarty.template}</b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;generated by Smarty template-engine v{$smarty.version}</i></span>
  </div>
{/if}
 <script type="text/javascript" src="/javascripts/jquery/jquery-latest.min.js"></script>
</body>

{include file="footer.tpl"}
</html>
