<?php
const PATH_DELIMITER = '/';
const PATH_CURRENT_DIR = '.';
const PATH_PREVIOUS_DIR = '..';
// Paths
define('PATH_CODEBASE_ROOT', PATH_DELIMITER .'var'. PATH_DELIMITER .'www'. PATH_DELIMITER .'custom_codebase_v3'. PATH_DELIMITER);
const PATH_CODEBASE_CONFIG = PATH_CODEBASE_ROOT .'config'. PATH_DELIMITER;
const PATH_LOG = PATH_CODEBASE_ROOT .'log'. PATH_DELIMITER;
const SITE_LOGFILE = PATH_LOG . SITE_FILES_PREFIX .'.error_log';
const PATH_LANGUAGE = PATH_CODEBASE_ROOT .'language'. PATH_DELIMITER;
// Classes and libraries
const PATH_COMMON = PATH_CODEBASE_ROOT .'common'. PATH_DELIMITER;
const PATH_COMMON_CLASSES = PATH_COMMON .'classes'. PATH_DELIMITER;
const PATH_COMMON_MODEL = PATH_COMMON_CLASSES .'model'. PATH_DELIMITER;
const PATH_COMMON_RENDERS = PATH_COMMON_CLASSES .'renderes'. PATH_DELIMITER;
const PATH_COMMON_CONTROLLERS = PATH_COMMON_CLASSES .'controller'. PATH_DELIMITER;
const PATH_COMMON_IMPORT = PATH_COMMON_CLASSES .'import'. PATH_DELIMITER;
// Database-abstractions
const PATH_COMMON_DB = PATH_COMMON_CLASSES .'db'. PATH_DELIMITER;
// Common Library
const PATH_COMMON_LIBARAY = PATH_COMMON .'library'. PATH_DELIMITER;
const PATH_LIBARAY_SMARTY = PATH_COMMON_LIBARAY .'smarty'. PATH_DELIMITER .'smarty-4.2.1'. PATH_DELIMITER .'libs'. PATH_DELIMITER;
const PATH_LIBARAY_JPGRAPH = PATH_COMMON_LIBARAY .'jpgraph'. PATH_DELIMITER .'jpgraph-4.4.1'. PATH_DELIMITER .'src'. PATH_DELIMITER;
const PATH_LIBARAY_PHPMAILER = PATH_COMMON_LIBARAY .'phpmailer'. PATH_DELIMITER .'phpmailer-6.6.4'. PATH_DELIMITER;
// Common location of Smarty-templates
const PATH_TEMPLATES = PATH_CODEBASE_ROOT .PATH_DELIMITER .'templates'. PATH_DELIMITER;
const PATH_TEMPLATES_STANDARD = PATH_TEMPLATES .'standard'. PATH_DELIMITER;
const PATH_TEMPLATES_DOMAIN = PATH_TEMPLATES .'site_templates'. PATH_DELIMITER;