<?php
const APP_DEBUG_MODE =FALSE;
const APP_ROOT_PATH = DIRECTORY_SEPARATOR .'data' .DIRECTORY_SEPARATOR .'WebProjects'. DIRECTORY_SEPARATOR .'Northern-partners'. DIRECTORY_SEPARATOR .'Projekt-timeseddler' .DIRECTORY_SEPARATOR .'app-time-registration'. DIRECTORY_SEPARATOR;
const CODEBASE_ROOT_PATH = APP_ROOT_PATH .'my_codebase'. DIRECTORY_SEPARATOR;
const APP_LANGUAGE_IDENT ='da';
const APP_DEFAULT_CHARSET = 'utf8';
const APP_DOMAIN_TITLE = '%s | Ivanonof.dk';
const SITE_DOMAIN_NAME = 'ivanonof.dk';
const APP_LOG_PATH = APP_ROOT_PATH .'log'. DIRECTORY_SEPARATOR;
const APP_ROUTES_PATH = APP_ROOT_PATH .'routes'. DIRECTORY_SEPARATOR;
const APP_LANGUAGE_PATH = APP_ROOT_PATH .'language'. DIRECTORY_SEPARATOR;
const APP_LOGFILE = APP_LOG_PATH .'app-errors.log';